export { authorRouter as author } from './author'
export { channelRouter as channel } from './channel'
export { channelTest } from './channel-test'
export { chapterRouter as chapter } from './chapter'
export { collegeOrBranchRouter as collegeOrBranch } from './college-or-branch'
export { couponRouter as coupon } from './coupon'
export { preferenceRouter as preference } from './preference'
export { studyMaterialRouter as studyMaterial } from './study-material'
export { subscriptionRouter as subscription } from './subscription'
export { videoRouter as video } from './video'
